---
# kubectl create cm mongodb-configmap \
# --from-literal database_url: "mongodb://username:password@mongodb-svc:27017"
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data: 
  database_url: "mongodb://username:password@mongodb-svc:27017"


