---
kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: mainui-rs
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: apache
  template:
    metadata:
      name: mainui-pod
      labels:
        name: apache
        app: main
        rel: stable
    spec:
      containers:
      - image:  httpd:2.2
        name: mainui-container
        ports:
        - containerPort: 80

